### ISSUE TITLE
OSError: [Errno 7] Argument list too long: 'gh'

### ISSUE THREAD

**Issue by bugcy013** [Chili-Piper/trivy-report-issue-action#3]
Hi @b34rd-tek  / @KadekM 

When we run the action, I am getting this exception 

```
4cd98f:9f6d6a52a81f4b31b7258e5dda67f792
2022-08-05T05:52:22.2396177Z Traceback (most recent call last):
2022-08-05T05:52:22.2396570Z GitHub Token: ***
2022-08-05T05:52:22.2397937Z   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2022-08-05T05:52:22.2399234Z Executing: gh --repo "dhana-prepaid/passportServices" issue list --label "vulnerability" --json title --jq .
2022-08-05T05:52:22.2400366Z     return _run_code(code, main_globals, None,
2022-08-05T05:52:22.2400913Z Creating GitHub PR Comments for dhana-prepaid/passportServices pull request 31
2022-08-05T05:52:22.2401987Z   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
2022-08-05T05:52:22.2402512Z gh --repo "dhana-prepaid/passportServices" pr comment 31" --body ... " 
2022-08-05T05:52:22.2403049Z     exec(code, run_globals)
2022-08-05T05:52:22.2403474Z   File "/trivy_report/report_issues.py", line 149, in <module>
2022-08-05T05:52:22.2403852Z     main()
2022-08-05T05:52:22.2404209Z   File "/trivy_report/report_issues.py", line 100, in main
2022-08-05T05:52:22.2404611Z     proc = subprocess.Popen(
2022-08-05T05:52:22.2405048Z   File "/usr/local/lib/python3.10/subprocess.py", line 969, in __init__
2022-08-05T05:52:22.2405531Z     self._execute_child(args, executable, preexec_fn, close_fds,
2022-08-05T05:52:22.2406002Z   File "/usr/local/lib/python3.10/subprocess.py", line 1845, in _execute_child
2022-08-05T05:52:22.2406485Z     raise child_exception_type(errno_num, err_msg, err_filename)
2022-08-05T05:52:22.2407027Z OSError: [Errno 7] Argument list too long: 'gh'
2022-08-05T05:52:22.3971767Z Post job cleanup.
```

can you please help on this.

Thanks
-Dhanasekaran

**Comment by james-luther** [comment]
Hi! Thanks for the comment! We ran into this also shortly after the Trivy action was updated and GitHub made some changes to the way it provides tokens. Because of these changes, we are planning on rebuilding this action completely based on the newer guidelines from GitHub. The error you're having actually isn't too difficult to fix, it looks like for the PR comment the argument list is too long. What can be done there is for each finding it can create another comment or something similar. For now I'd recommend trying without running on PR. It should still generate issues as needed. The newer version should be ready in September.

**Comment by saerosV** [comment]
Hi @b34rd-tek.

Any news regarding the new version of this Action?

Thanks.

**Comment by james-luther** [comment]
I think it is going to be discontinued. We were using it previously but have now moved to the normal Trivy action and have steps that include action summary, scan reports, and publishing results to our vulnerability tracking system.

**Comment by saerosV** [comment]
@b34rd-tek got it, thanks for clarifying.

Just out of curiosity, which vulnerability tracking system would that be? Is it something that could be integrated into GitHub?
